[build]
  publish = "." # Tells Netlify your index.html is in the main folder

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["axios", "form-data"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
